version: 2

jobs:
  "build-prod":
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      # Initialization.
      - run:
          name: checking out build repo
          command: git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: apk add --no-cache bash openssl

      # Restoration of node_modules from cache.
      - restore_cache:
          key: docker-tc-ragnar-service-{{ checksum "package-lock.json" }}

      # Build of Docker image.
      - run:
          name: Build of Docker image
          command: ./build.sh PROD

      # Caching node modules.
      - save_cache:
          key: docker-tc-ragnar-service-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Deployment.
      - run:
          name: Installing AWS client
          command: |
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade

      - deploy:
          command: |
            echo "ntegration testing" 
            cp ./../buildscript/master_deploy.sh .
            ./master_deploy.sh -d ECS -e PROD -t $CIRCLE_SHA1 -s GIT -p TDJSON


workflows:
  version: 2
  build:
    jobs:
      # Production builds are executed on "master" branch only.
      - "build-prod":
          filters:
            branches:
              only: "master"